Repository AlexOneZ/SiriusGame, pull requests merged in 2025-04, with the labels that each got.

#94 Task 78/1 - список соревнований для каждой команды
  README.md
  backend/.gitignore
  backend/database.db
  backend/database.py
  backend/events/repository.py
  backend/events/router.py
  backend/events/schemas.py
  backend/requirements.txt
  backend/teams/repository.py
  backend/teams/router.py
  backend/teams/schemas.py
Labels: help wanted

#118 fix: fields sounds and destination
  backend/database.db
  backend/pushes/router.py
  backend/pushes/schemas.py
  backend/pushes/services.py
Labels: bug

#122 feat: push history for devices and delete pushes from history
  backend/database.db
  backend/database.py
  backend/pushes/handler.py
  backend/pushes/repository.py
  backend/pushes/router.py
  backend/pushes/schemas.py
Labels: enhancement
